package com.hotelcheckin.hotel.model;


import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class Room {

    private int roomNumber;
    private RoomType roomType;
    private boolean available;

    public Room(int roomNumber, RoomType roomType, boolean available) {
        this.roomNumber = roomNumber;
        this.roomType = roomType;
        this.available = available;
    }

    //Getters and setters generated by LOMBOK.
    /*
    DATA - Get & Set
     */

}
